services:
  spark:
    image: spark:3.4.1
    container_name: spark
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-master.sh && tail -f /dev/null"]
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - PATH=/opt/spark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: agri_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
